@file:Suppress("EmptyMethod")

package com.naminfo.ui.main.chat.viewmodel

import androidx.annotation.UiThread
import androidx.annotation.WorkerThread
import androidx.lifecycle.MutableLiveData
import com.naminfo.DiyaOneApplication.Companion.coreContext
import com.naminfo.R
import org.linphone.core.Address
import org.linphone.core.ChatRoom
import org.linphone.core.Conference
import org.linphone.core.ConferenceListenerStub
import org.linphone.core.MediaDirection
import org.linphone.core.tools.Log
import com.naminfo.ui.GenericViewModel
import com.naminfo.utils.Event
import com.naminfo.utils.LinphoneUtils

abstract class AbstractConversationViewModel : GenericViewModel() {
    companion object {
        private const val TAG = "[Abstract Conversation ViewModel]"
    }

    val chatRoomFoundEvent: MutableLiveData<Event<Boolean>> by lazy {
        MutableLiveData()
    }

    val confirmGroupCallEvent: MutableLiveData<Event<Boolean>> by lazy {
        MutableLiveData()
    }

    lateinit var chatRoom: ChatRoom

    lateinit var conversationId: String

    private val conferenceListener = object : ConferenceListenerStub() {
        @WorkerThread
        override fun onStateChanged(conference: Conference, newState: Conference.State?) {
            Log.i("$TAG Conference state changed [$newState]")
            when (newState) {
                Conference.State.CreationFailed -> {
                    showRedToast(R.string.conference_failed_to_create_group_call_toast, R.drawable.warning_circle)
                    conference.removeListener(this)
                }
                Conference.State.Created -> {
                    conference.removeListener(this)
                }
                else -> {}
            }
        }
    }

    fun isChatRoomInitialized(): Boolean {
        return ::chatRoom.isInitialized
    }

    @WorkerThread
    open fun beforeNotifyingChatRoomFound(sameOne: Boolean) {
    }

    @WorkerThread
    open fun afterNotifyingChatRoomFound(sameOne: Boolean) {
    }

    @UiThread
    fun findChatRoom(room: ChatRoom?, conversationId: String) {
        coreContext.postOnCoreThread { core ->
            Log.i("$TAG Looking for conversation with conversation ID [$conversationId]")
            if (room != null && ::chatRoom.isInitialized && chatRoom == room) {
                Log.i("$TAG Conversation object already in memory, skipping")

                this@AbstractConversationViewModel.conversationId = conversationId
                beforeNotifyingChatRoomFound(sameOne = true)
                chatRoomFoundEvent.postValue(Event(true))
                afterNotifyingChatRoomFound(sameOne = true)

                return@postOnCoreThread
            }

            if (room != null && (!::chatRoom.isInitialized || chatRoom != room)) {
                if (conversationId == LinphoneUtils.getConversationId(room)) {
                    Log.i("$TAG Conversation object available in sharedViewModel, using it")
                    chatRoom = room

                    this@AbstractConversationViewModel.conversationId = conversationId
                    beforeNotifyingChatRoomFound(sameOne = false)
                    chatRoomFoundEvent.postValue(Event(true))
                    afterNotifyingChatRoomFound(sameOne = false)

                    return@postOnCoreThread
                }
            }

            if (conversationId.isNotEmpty()) {
                Log.i("$TAG Searching for conversation in Core using local & peer SIP addresses")
                // Basic chat identifiers generated by Linphone normalize away the
                // default SIP port. Prefer our exact identifier so a notification
                // for the :5060 room can't reopen the equivalent no-port room.
                val found = core.chatRooms.find {
                    LinphoneUtils.getConversationId(it) == conversationId
                }
                    ?: core.searchChatRoomByIdentifier(conversationId)
                if (found != null) {
                    this@AbstractConversationViewModel.conversationId = conversationId
                    if (::chatRoom.isInitialized && chatRoom == found) {
                        Log.i("$TAG Conversation object already in memory, keeping it")
                        beforeNotifyingChatRoomFound(sameOne = true)
                        chatRoomFoundEvent.postValue(Event(true))
                        afterNotifyingChatRoomFound(sameOne = true)
                    } else {
                        chatRoom = found
                        Log.i("$TAG Found conversation in Core, using it")

                        beforeNotifyingChatRoomFound(sameOne = false)
                        chatRoomFoundEvent.postValue(Event(true))
                        afterNotifyingChatRoomFound(sameOne = false)
                    }
                } else {
                    Log.e("$TAG Failed to find conversation given local & remote addresses!")
                    chatRoomFoundEvent.postValue(Event(false))
                }
            } else {
                Log.e("$TAG Failed to parse local or remote SIP URI as Address!")
                chatRoomFoundEvent.postValue(Event(false))
            }
        }
    }

    private var groupCallWithVideo = false

    @UiThread
    fun startCall() = startCallWithVideo(false)

    @UiThread
    fun startVideoCall() = startCallWithVideo(true)

    private fun startCallWithVideo(video: Boolean) {
        coreContext.postOnCoreThread {
            if (!::chatRoom.isInitialized) return@postOnCoreThread
            groupCallWithVideo = video
            if (LinphoneUtils.isChatRoomAGroup(chatRoom) && chatRoom.participants.size >= 2) {
                confirmGroupCallEvent.postValue(Event(true))
            } else {
                val firstParticipant = chatRoom.participants.firstOrNull()
                val address = firstParticipant?.address ?: chatRoom.peerAddress
                if (address != null) {
                    Log.i("$TAG Calling SIP address [${address.asStringUriOnly()}], video [$video]")
                    if (video) {
                        coreContext.startVideoCall(address, localAddress = chatRoom.localAddress)
                    } else {
                        coreContext.startAudioCall(address, localAddress = chatRoom.localAddress)
                    }
                } else {
                    Log.e("$TAG Failed to find participant to call!")
                }
            }
        }
    }

    @UiThread
    fun startGroupCall() {
        coreContext.postOnCoreThread { core ->
            val account = chatRoom.account ?: core.defaultAccount
            if (account == null) {
                Log.e(
                    "$TAG No default account found, can't create group call!"
                )
                return@postOnCoreThread
            }

            val conference = LinphoneUtils.createGroupCall(account, chatRoom.subjectUtf8.orEmpty())
            if (conference == null) {
                Log.e("$TAG Failed to create group call!")
                showRedToast(R.string.conference_failed_to_create_group_call_toast, R.drawable.warning_circle)
                return@postOnCoreThread
            }

            val callParams = core.createCallParams(null)
            callParams?.isVideoEnabled = groupCallWithVideo
            callParams?.videoDirection = if (groupCallWithVideo) MediaDirection.SendRecv else MediaDirection.Inactive

            val participants = arrayOfNulls<Address>(chatRoom.participants.size)
            var index = 0
            for (participant in chatRoom.participants) {
                participants[index] = participant.address
                index += 1
            }
            Log.i(
                "$TAG Inviting ${participants.size} participant(s) into newly created conference"
            )
            if (conference.inviteParticipants(participants, callParams) != 0) {
                Log.e("$TAG Failed to invite participants into group call!")
                showRedToast(R.string.conference_failed_to_create_group_call_toast, R.drawable.warning_circle)
            } else {
                conference.addListener(conferenceListener)
            }
        }
    }
}
